### ISSUE TITLE
autoproj2.0: install failes on fresh debian stable

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/autoproj#100]
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
bootstrap: 4: bootstrap: autoreconf: not found
post-autoconf.rb:6:in `initialize': No such file or directory @ rb_sysopen - configure (Errno::ENOENT)
	from post-autoconf.rb:6:in `open'
	from post-autoconf.rb:6:in `process'
	from post-autoconf.rb:16:in `<main>'
Post-processing configure
sh: 0: Can't open configure

Makefile not found

Gem files will remain installed in /home/goldhoorn/.gem/ruby/2.1.0/gems/rice-1.7.0 for inspection.
Results logged to /home/goldhoorn/.gem/ruby/2.1.0/extensions/x86_64-linux/2.1.0/rice-1.7.0/gem_make.out
An error occurred while installing rice (1.7.0), and Bundler cannot continue.
Make sure that `gem install rice -v '1.7.0'` succeeds before bundling.
```

See: http://www.goldhoorn.eu/extern/autoproj-debian-stable-osdeps.log

**Comment by doudou** [comment]
Welll ... does the rice osdep install autoconf ?

**Comment by doudou** [comment]
And for that matter, does it install the ruby dev packages ? Because autoproj does not anymore since utilrb is not part of the autoproj install.

**Comment by doudou** [comment]
Just tested on 2.0.rc21 on a fresh ubuntu install ... seems to be fixed.
