### ISSUE TITLE
Autoproj prints a backtrace

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj#152]
I have noticed that when an error occurs (interruption due to a CTRL-C or package update/build error) autoproj now prints a full backtrace of the exception rather than a pretty print of the exception message. Was this change in the behavior intentional ?

**Comment by doudou** [comment]
> Was this change in the behavior intentional ?

No

**Comment by doudou** [comment]
Could you have a look at https://github.com/rock-core/autoproj/pull/153 ?

I couldn't reproduce with build/update error, only with CTRL+C

**Comment by g-arjones** [comment]
Just did.. I can't consistently reproduce it in build/update errors as well but I still get these even that patch:

```  already up-to-date bir.flat_fish.br
  already up-to-date orocos.toolchain         
  interrupted bir.flat_fish                   
                                    
Interrupted by user
/home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/subcommand.rb:391:in `each_line': Interrupt
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/subcommand.rb:391:in `block in run'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/subcommand.rb:274:in `open'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/subcommand.rb:274:in `run'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/package.rb:540:in `run'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/import/git.rb:432:in `run_git_bare'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/import/git.rb:421:in `run_git_bare'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/import/git.rb:526:in `fetch_remote'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/import/git.rb:598:in `current_remote_commit'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/import/git.rb:978:in `determine_target_state'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/import/git.rb:998:in `update'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/importer.rb:304:in `perform_update'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/importer.rb:433:in `block in import'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/package.rb:380:in `isolate_errors'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/importer.rb:431:in `import'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/ops/tools.rb:28:in `import'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/ops/configuration.rb:82:in `update_configuration_repository'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/ops/configuration.rb:132:in `update_remote_package_set'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/ops/configuration.rb:231:in `block in load_and_update_package_sets'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/ops/configuration.rb:399:in `handle_keep_going'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/ops/configuration.rb:230:in `load_and_update_package_sets'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/ops/configuration.rb:589:in `update_package_sets'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/ops/configuration.rb:441:in `update_configuration'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/ops/configuration.rb:382:in `load_package_sets'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/workspace.rb:475:in `load_package_sets'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/cli/update.rb:81:in `run'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/cli/main.rb:46:in `block in run_autoproj_cli'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/reporter.rb:68:in `block in report'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/reporting.rb:285:in `report'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/reporter.rb:66:in `report'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/cli/main.rb:36:in `run_autoproj_cli'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/cli/main.rb:147:in `update'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/bin/aup:15:in `<top (required)>'
	from /home/arjones/flat_fish/dev/.autoproj/bin/aup:15:in `load'
	from /home/arjones/flat_fish/dev/.autoproj/bin/aup:15:in `<main>'
```

**Comment by g-arjones** [comment]
The backtrace is slightly different if the interrupt takes place in a package (rather than in a package set):

```  interrupted base/logging                                                   
  interrupted base/console_bridge                                             
  interrupted base/cmake                                                 
  updating base/numeric, base/orogen/std, base/orogen/types^C             
  interrupted base/orogen/types                                                 
  updating base/numeric, base/orogen/std, base/scripts                           
  base/orogen/std                                              
  base/numeric                                         
  updating base/scripts/home/arjones/.autoproj/gems/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:43:in `sleep': Interrupt
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:43:in `wait'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:43:in `ns_wait'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/abstract_lockable_object.rb:43:in `ns_wait_until'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/event.rb:87:in `block in wait'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/event.rb:84:in `wait'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_executor_service.rb:49:in `wait_for_termination'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/ops/import.rb:331:in `ensure in import_selected_packages'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/ops/import.rb:331:in `import_selected_packages'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/ops/import.rb:395:in `import_packages'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/cli/update.rb:190:in `update_packages'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/cli/update.rb:110:in `run'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/cli/main.rb:46:in `block in run_autoproj_cli'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/reporter.rb:68:in `block in report'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.12.0/lib/autobuild/reporting.rb:285:in `report'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/reporter.rb:66:in `report'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/cli/main.rb:36:in `run_autoproj_cli'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/lib/autoproj/cli/main.rb:147:in `update'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.3.0/bin/aup:15:in `<top (required)>'
	from /home/arjones/flat_fish/dev/.autoproj/bin/aup:15:in `load'
	from /home/arjones/flat_fish/dev/.autoproj/bin/aup:15:in `<main>'```

**Comment by doudou** [comment]
Have you applied the other PR ?

**Comment by g-arjones** [comment]
Yep.. use aup/amake rather than autoproj update/autoproj build and you should be able to reproduce

**Comment by doudou** [comment]
> Yep.. use aup/amake rather than autoproj update/autoproj build and you should be able to reproduce

This is what I noticed, and then added a "rescue Interrupt" at the toplevel of aup, amake and alocate in #153. Just to be sure that there is no confusion: there are two PRs. One in autobuild for the color stuff, one in autoproj (#153) for the Interrupt backtrace.

**Comment by g-arjones** [comment]
Ooops.. The one in autoproj does fix it. Sorry about the confusion...
