### ISSUE TITLE
Exceptions leaking to the user

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj#154]
Found another one:

```
arjones@elementaryOS:~/flat_fish/dev/drivers/orogen/ecomm_board$ aup package-not-found
  operating system: elementary,ubuntu,debian - 0.4.1,loki
/home/arjones/.autoproj/gems/ruby/2.3.0/bundler/gems/autoproj-1c5cbe6c0118/lib/autoproj/cli/base.rb:154:in `validate_user_selection': autoproj: wrong package selection on command line, cannot find a match for package-not-found (Autoproj::ConfigError)
	from /home/arjones/.autoproj/gems/ruby/2.3.0/bundler/gems/autoproj-1c5cbe6c0118/lib/autoproj/cli/update.rb:155:in `finish_loading_configuration'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/bundler/gems/autoproj-1c5cbe6c0118/lib/autoproj/cli/update.rb:98:in `run'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/bundler/gems/autoproj-1c5cbe6c0118/lib/autoproj/cli/main.rb:46:in `block in run_autoproj_cli'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/bundler/gems/autoproj-1c5cbe6c0118/lib/autoproj/reporter.rb:68:in `block in report'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/bundler/gems/autobuild-5e46b23fdee9/lib/autobuild/reporting.rb:285:in `report'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/bundler/gems/autoproj-1c5cbe6c0118/lib/autoproj/reporter.rb:66:in `report'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/bundler/gems/autoproj-1c5cbe6c0118/lib/autoproj/cli/main.rb:36:in `run_autoproj_cli'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/bundler/gems/autoproj-1c5cbe6c0118/lib/autoproj/cli/main.rb:147:in `update'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/arjones/.autoproj/gems/ruby/2.3.0/bundler/gems/autoproj-1c5cbe6c0118/bin/aup:16:in `<top (required)>'
	from /home/arjones/flat_fish/dev/.autoproj/bin/aup:15:in `load'
	from /home/arjones/flat_fish/dev/.autoproj/bin/aup:15:in `<main>'
```

**Comment by doudou** [comment]
Yeah, there's really a big bunch of these.

#155 should fix most of them. If you could apply it to your local tree, to get it tested a little bit more before I release it, that would be great. I'll try to add unit tests for all the changes in the commit before then, but might not have the time :(

**Comment by doudou** [comment]
AFAIK, this is fixed.
