### ISSUE TITLE
uninitialized constant Thor::DidYouMean::SpellChecker (NameError)

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-core/autoproj#223]
I don't know what is happening here:

```
amake
/home/afabisch/.autoproj/gems/ruby/2.3.0/gems/thor-0.20.1/lib/thor/error.rb:12:in `<module:DidYouMean>': uninitialized constant Thor::DidYouMean::SpellChecker (NameError)
        from /home/afabisch/.autoproj/gems/ruby/2.3.0/gems/thor-0.20.1/lib/thor/error.rb:6:in `<class:Thor>'
        from /home/afabisch/.autoproj/gems/ruby/2.3.0/gems/thor-0.20.1/lib/thor/error.rb:1:in `<top (required)>'
        from /home/afabisch/.autoproj/gems/ruby/2.3.0/gems/thor-0.20.1/lib/thor/base.rb:4:in `require'
        from /home/afabisch/.autoproj/gems/ruby/2.3.0/gems/thor-0.20.1/lib/thor/base.rb:4:in `<top (required)>'
        from /home/afabisch/.autoproj/gems/ruby/2.3.0/gems/thor-0.20.1/lib/thor.rb:2:in `require'
        from /home/afabisch/.autoproj/gems/ruby/2.3.0/gems/thor-0.20.1/lib/thor.rb:2:in `<top (required)>'
        from /home/afabisch/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/lib/autoproj/cli/main.rb:1:in `require'
        from /home/afabisch/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/lib/autoproj/cli/main.rb:1:in `<top (required)>'
        from /home/afabisch/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/bin/amake:3:in `require'
        from /home/afabisch/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/bin/amake:3:in `<top (required)>'
        from /home/afabisch/Projekte/cdff/.autoproj/bin/amake:32:in `load'
        from /home/afabisch/Projekte/cdff/.autoproj/bin/amake:32:in `<main>'
```

Any call to autoproj triggers this error. Any idea? Did the thor gem have any breaking changes?

**Comment by AlexanderFabisch** [comment]
OK, I installed the latest version with `gem install thor` and removed the folder with `rm -r ~/.autoproj/gems/ruby/2.3.0/gems/thor-0.20.1`. Now it seems to work.
