### ISSUE TITLE
sanity check in sort_package_sets_by_import_order fails in some cases

### ISSUE THREAD

**Issue by vbargsten** [rock-core/autoproj#328]
The following exception is triggered in some cases:
https://github.com/rock-core/autoproj/blob/700ae181206fbb6bb3560bf914e423582d8c8a11/lib/autoproj/ops/configuration.rb#L370

My theory is, root_pkg_set / "main configuration" is inserted just after the last explicit import, but there can be further imported dependencies if the last explicit package set has dependencies. Somehow the implicit dependencies seem to not being propagated properly to the root package set. A workaround is to add root pkg set also to the "target list" 

https://github.com/vbargsten/autoproj/commit/363008fab3c675f36664f62f4d3be7fe048fe8ca#diff-86d73a3e07d681adc4f4e2efba488f6709905a27818933f9a89b02cf2cbafbb2

**Comment by doudou** [comment]
This is ... very possible. I haven't personally been using package set dependencies. Can you try to create a reproducing build configuration ? That would help a lot.

**Comment by vbargsten** [comment]
It seems to happen in chained imports but also depends on the explicit import. Here is a bash script to create a minimal example triggering the error on my system:

```bash

#!/bin/bash

set -e 

mkdir /tmp/autoproj_debug_pkg_import_order
cd /tmp/autoproj_debug_pkg_import_order
mkdir buildconf
mkdir pkg_set_a
mkdir pkg_set_b
mkdir pkg_set_c
mkdir bootstrap


cd buildconf
git init .

cat <<EOF > manifest
package_sets:
   - type: git
     url: /tmp/autoproj_debug_pkg_import_order/pkg_set_a
     branch: master
   - type: git
     url: /tmp/autoproj_debug_pkg_import_order/pkg_set_c
     branch: master

layout: []
EOF

git add manifest
git commit -m "manifest added"
cd ..


cd pkg_set_a
git init .

cat <<EOF > source.yml
name: pkg_set_a
imports:
   - type: git
     url: /tmp/autoproj_debug_pkg_import_order/pkg_set_b
     branch: master
EOF

git add source.yml
git commit -m "source.yml added"
cd ..


cd pkg_set_b
git init .

cat <<EOF > source.yml
name: pkg_set_b
imports:
   - type: git
     url: /tmp/autoproj_debug_pkg_import_order/pkg_set_c
     branch: master
EOF

git add source.yml
git commit -m "source.yml added"
cd ..

cd pkg_set_c
git init .

cat <<EOF > source.yml
name: pkg_set_c
EOF

git add source.yml
git commit -m "source.yml added"
cd ..

wget 'https://raw.githubusercontent.com/rock-core/autoproj/master/bin/autoproj_bootstrap'
cd bootstrap
ruby ../autoproj_bootstrap git /tmp/autoproj_debug_pkg_import_order/buildconf

# then do 
# cd /tmp/autoproj_debug_pkg_import_order/bootstrap/
# . env.sh 
# aup --verbose

```


I added some debug output into the method:
```ruby
        def sort_package_sets_by_import_order(package_sets, root_pkg_set)
            # The sorting is done in two steps:
            #  - first, we build a topological order of the package sets
            #  - then, we insert the auto-imported packages, following this
            #    topological order, in the user-provided order. Each package is
            #    considered in turn, and added at the earliest place that fits
            #    the dependencies
            topological = Array.new
            queue = (package_sets.to_a + [root_pkg_set]).uniq
            while !queue.empty?
                last_size = queue.size
                pending = queue.dup
                queue = Array.new
                while !pending.empty?
                    pkg_set = pending.shift
                    if pkg_set.imports.any? { |imported_set| !topological.include?(imported_set) }
                        queue.push(pkg_set)
                    else
                        topological << pkg_set
                    end
                end
                if queue.size == last_size
                    raise ArgumentError, "cannot resolve the dependencies between package sets. There seem to be a cycle amongst #{queue.map(&:name).sort.join(", ")}"
                end
            end

            topological.each do |p|
                puts "Topo Pack #{p.name}"
            end
            
            result = root_pkg_set.imports.to_a.dup# + [root_pkg_set]
            to_insert = topological.dup.
                find_all { |p| !result.include?(p) }
            while !to_insert.empty?
                pkg_set = to_insert.shift
                puts "Checking pack set #{pkg_set.name}"
                result.each do |p|
                    puts "Result Pack before #{p.name}"
                end
                dependencies = pkg_set.imports.dup
                
                if dependencies.empty?
                    result.unshift(pkg_set)
                    puts "    no deps, putting back"
                else
                    i = result.find_index do |p|
                        puts "    Deleting #{p.name} from deps"
                        dependencies.delete(p)
                        dependencies.empty?
                    end
                    puts "    inserting #{pkg_set.name} at #{i+1}, currently #{result.size}"
                    result.insert(i + 1, pkg_set)
                end
                result_str = ""
                result.each do |p|
                    puts "Result Pack after #{p.name}"
                    result_str += "#{p.name},"
                end
            end
            
            # Sanity check related to the root package set
            # - it should be last
            # - it should be present only once
            if result.last != root_pkg_set
                raise InternalError, "failed to sort the package sets: the root package set should be last, but is not #{result_str}"
            end
            result
        end
```

This is what I get then:

```
Topo Pack pkg_set_c
Topo Pack pkg_set_b
Topo Pack pkg_set_a
Topo Pack main configuration
Checking pack set pkg_set_b
Result Pack before pkg_set_a
Result Pack before pkg_set_c
    Deleting pkg_set_a from deps
    Deleting pkg_set_c from deps
    inserting pkg_set_b at 2, currently 2
Result Pack after pkg_set_a
Result Pack after pkg_set_c
Result Pack after pkg_set_b
Checking pack set main configuration
Result Pack before pkg_set_a
Result Pack before pkg_set_c
Result Pack before pkg_set_b
    Deleting pkg_set_a from deps
    Deleting pkg_set_c from deps
    inserting main configuration at 2, currently 3
Result Pack after pkg_set_a
Result Pack after pkg_set_c
Result Pack after main configuration
Result Pack after pkg_set_b
Traceback (most recent call last):
        18: from /tmp/autoproj_debug_pkg_import_order/bootstrap/.autoproj/bin/aup:51:in `<main>'
        17: from /tmp/autoproj_debug_pkg_import_order/bootstrap/.autoproj/bin/aup:51:in `load'
        16: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.13.0/bin/aup:17:in `<top (required)>'
        15: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        14: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        13: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        12: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        11: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.13.0/lib/autoproj/cli/main.rb:240:in `update'
        10: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.13.0/lib/autoproj/cli/main.rb:128:in `run_autoproj_cli'
         9: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.13.0/lib/autoproj/reporter.rb:107:in `report'
         8: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/autobuild-1.21.0/lib/autobuild/reporting.rb:103:in `report'
         7: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.13.0/lib/autoproj/reporter.rb:110:in `block in report'
         6: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.13.0/lib/autoproj/cli/main.rb:139:in `block in run_autoproj_cli'
         5: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.13.0/lib/autoproj/cli/update.rb:85:in `run'
         4: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.13.0/lib/autoproj/workspace.rb:640:in `load_package_sets'
         3: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.13.0/lib/autoproj/ops/configuration.rb:405:in `load_package_sets'
         2: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.13.0/lib/autoproj/ops/configuration.rb:464:in `update_configuration'
         1: from /home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.13.0/lib/autoproj/ops/configuration.rb:641:in `update_package_sets'
/home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.13.0/lib/autoproj/ops/configuration.rb:393:in `sort_package_sets_by_import_order': failed to sort the package sets: the root package set should be last, but is not pkg_set_a,pkg_set_c,main configuration,pkg_set_b, (Autoproj::InternalError)

```
